// Source: adiciones_layout/source/Sellos/c_sello_notas_sct_marg_sub.magik
// Sello de notas SCT para instalación marginal subterránea (notas 1-15).
// Hereda notas 1-4 del padre y añade notas 5-15 específicas.
// Es la variante más larga de la familia: usa tipoCable, estado E instalacion.

import {
  CSelloNotasSct,
  type SelloNotasSctConfig,
  type TableConfig,
} from './CSelloNotasSct';

// Magik: override de prvCrea_Cfg_Tbl_Notas_Grales
// fila 2 = 265 mm (la más alta de la familia), col 1 = 170 mm
export const TABLE_CONFIG_MARG_SUB: TableConfig = {
  rowTitle: 10,
  rowText:  265,
  colWidth: 170,
};

export class CSelloNotasSctMargSub extends CSelloNotasSct {
  static override readonly allowedOnMenu = false;

  override get tableConfig(): TableConfig {
    return TABLE_CONFIG_MARG_SUB;
  }

  // Magik: prvAsignaTexto — llama a super luego concatena notas 5-15
  // A diferencia de las otras subclases, usa tipoCable, estado E instalacion
  override buildTexto(): string {
    const base = super.buildTexto();
    const c = this._tipoCable;
    const e = this._estado;
    const i = this._instalacion;

    const extra = [
      ` 5.- LA UBICACIÓN DE LA INSTALACIÓN MARGINAL ${i} CON CABLE DE ${c}\n` +
      ` INDICADA EN ESTE PROYECTO DEBERÁ SER VERIFICADO Y PRECISADO EN EL LUGAR POR LA RESIDENCIA\n` +
      ` GENERAL DE CONSERVACIÓN DE CARRETERAS EN EL ESTADO DE ${e}.`,

      ` 6.- LA INSTALACIÓN MARGINAL ${i} CON CABLE DE ${c}\n` +
      ` QUE SE INDICA EN ESTE PROYECTO DEBERÁ EFECTUARSE CONFORME A LAS INDICACIONES ADICIONALES \n` +
      ` DE LA RESIDENCIA GENERAL DE CONSERVACIÓN DE CARRETERAS, ASÍ COMO LAS RECOMENDACIONES QUE \n` +
      ` SEAN DERIVADAS DE LAS INSPECCIONES EN CAMPO.`,

      ` 7.- LA INSTALACIÓN MARGINAL ${i} CON POSTES Y CABLE DE ${c}\n` +
      ` QUE SE INDICA EN ESTE PROYECTO DENTRO DEL ÁREA DEL DERECHO DE VÍA, DEBERÁ EFECTUARSE EN \n` +
      ` UNA FRANJA PARALELA AL EJE DEL CAMINO CON UN ANCHO NO MAYOR DE 2.50 M. MEDIDOS A PARTIR \n` +
      ` DEL LIMITE DEL DERECHO DE VÍA, SALVO EN LOS CASOS EN QUE LA PRESENCIA DE OBSTÁCULOS NA- \n` +
      ` TURALES IMPIDAN CUMPLIR CON ESTA ESPECIFICACIÓN. `,

      ` 8.- DENTRO DEL DERECHO DE VÍA, LA DISTANCIA ENTRE LA PARTE NATURAL DEL TERRENO O DE LA \n` +
      ` PARTE MAS BAJA DE LA SECCIÓN DEL CAMINO, SOBRE EL CABLE DE ${c} SERÁ DE 1.20 M. \n` +
      ` COMO MÍNIMO Y 1.50 M.  A PARTIR DEL FONDO DE LAS CUNETAS.`,

      ` 9.- LAS CUNETAS QUE SEAN AFECTADAS POR LA EXCAVACIÓN DE LA ZANJA PARA LA COLOCACIÓN DEL \n` +
      ` CABLE DE ${c} SERÁN RECONSTRUIDAS Y ZAMPEADAS, AÚN EN EL CASO EN QUE NO \n` +
      ` ESTEN ANTES DE SU AFECTACIÓN, PREVIAMENTE EL FILTRO AFECTADO DEBERÁ RESTITUIRSE CON LA \n` +
      ` GRANULOMETRIA ORIGINAL O LA INDICADA POR LA RESIDENCIA GENERAL DE CONSERVACIÓN DE CARRE-\n` +
      ` TERAS EN ESA ENTIDAD.`,

      ` 10.- EL RELLENO DE LA EXCAVACIÓN DEBERÁ HACERSE DE TAL MANERA QUE  EL TERRENO QUEDE EN \n` +
      ` CONDICIONES SEMEJANTES A LAS ORIGINALES.`,

      ` 11.- CUALQUIER DAÑO QUE SE OCASIONE AL PAVIMENTO, ACOTAMIENTO, CUNETA Y/O SEÑALAMIENTO, \n` +
      ` DEBERÁ SER REPARADO DE INMEDIATO, POR CUENTA DE TELÉFONOS DE MÉXICO, S.A. DE C.V. DE A- \n` +
      ` CUERDO A LAS INDICACIONES DE LA RESIDENCIA GENERAL DE CONSERVACIÓN DE CARRETERAS EN ESA \n` +
      ` ENTIDAD.`,

      ` 12.- PARA EVITAR ACCIDENTES DURANTE LA CONSTRUCCIÓN DE LA OBRA TELÉFONOS DE MÉXICO, S.A.\n` +
      ` DE C.V. COLOCARA Y CONSERVARA PERMANENTEMENTE EN EL CAMINO LAS SEÑALES PREVENTIVAS, RES-\n` +
      ` TRICTIVAS E INFORMATIVAS QUE INDIQUE LA RESIDENCIA GENERAL DE CONSERVACIÓN DE CARRETERAS\n` +
      ` CON BASE EN LO ESTABLECIDO EN EL 'MANUAL DE DISPOSITIVOS PARA EL CONTROL DEL TRANSITO EN\n` +
      ` CALLES Y CARRETERAS' EDITADO POR LA SCT EDICIÓN 1986; CON EL FIN DE EVITAR ACCIDENTES --\n` +
      ` NOCTURNOS, SE INSTALARA Y CONSERVARA PERMANENTEMENTE DURANTE TODA LA NOCHE, EL SEÑALA --\n` +
      ` MIENTO LUMINOSO CONSISTENTE EN LÁMPARAS DE DESTELLO Y OTROS DISPOSITIVOS LUMINOSOS.`,

      ` 13.- UNA VEZ TERMINADOS LOS TRABAJOS DE ESTA OBRA, DEBERÁN RETIRARSE FUERA DE LOS LIMITES\n` +
      ` DEL DERECHO DE VÍA, TODOS LOS MATERIALES SOBRANTES DE LA EXCAVACIÓN Y LOS DE CONSTRUCCIÓN\n` +
      ` DE LA OBRA, INCLUYENDO EL SEÑALAMIENTO DE MODO QUE LA CARRETERA Y LA ZONA DEL DERECHO DE \n` +
      ` VÍA QUEDEN EN SUS CONDICIONES ORIGINALES.`,

      ` 14.- LOS CRUZAMIENTOS SUBTERRÁNEOS CON CABLE DE ${c} QUE SE PRETENDAN E-\n` +
      ` FECTUAR DERIVADOS DE ESTA INSTALACIÓN MARGINAL ${i}, DEBERÁN SOLI-\n` +
      ` CITARSE POR SEPARADO, PRESENTANDO PLANO DETALLADO DEL PROYECTO DE LOS CRUZAMIENTOS.`,

      ` 15.- LAS INSTALACIONES LATERALES CON CABLE DE ${c} ADOSADAS A LOS PUENTES\n` +
      ` Y ALCANTARILLAS QUE TELÉFONOS DE MÉXICO, S.A. DE C.V. PRETENDA O REQUIERA ESTABLECER EN -\n` +
      ` EL TRAYECTO DE ESTA INSTALACIÓN MARGINAL ${i}, DEBERÁN SOLICITARSE \n` +
      ` POR SEPARADO, PRESENTANDO PLANO DETALLADO DE LA INSTALACIÓN.`,
    ].join('\n\n');

    return base + '\n\n' + extra;
  }
}

export type { SelloNotasSctConfig };
